name: walt_interview_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0  # For making HTTP requests to the backend
  cupertino_icons: ^1.0.8 # For iOS style icons
  path_provider: ^2.1.0 # For accessing local file storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: # <-- This is the SINGLE, CORRECT 'flutter:' section

  uses-material-design: true

  assets: # <-- Assets section correctly indented
    - assets/images/walt.png # <-- Path to your image, correctly indented
